routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.home');
});

Route::get('/test', function () {
    return view('layouts.frontend.master');
});

Route::get('/news', 'FrontController@indexNews');
Route::POST('/news', 'FrontController@StoreComment');
Route::get('/news/{id}', 'FrontController@detailNews');
Route::post('/news/{id}/comment', 'FrontController@commentNews');
Route::get('/news/pdf', 'FrontController@PdfFile');


Route::get('/news/detail', function () {
    return view('frontend.news.detail');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/master', function () {
//     return view('sbadmin2.gambar');
// });

//ini hanya contoh boleh dihapus (Makki)
// Route::get('/profile',function(){
// 	return view('sbadmin2.menu.profile');
// });

// Route::get('/news', function () {
//     return view('sbadmin2.menu.news');
// });
// Route::get('/comment', function () {
//     return view('sbadmin2.menu.comment');
// });
// Route::get('/download', function () {
//     return view('sbadmin2.menu.download');
// });


// Route::get('/news', function () {
//     return view('sbadmin2.menu.news');
// });
// Route::get('/comment', function () {
//     return view('sbadmin2.menu.comment');
// });
// Route::get('/download', function () {
//     return view('sbadmin2.menu.download');
// });


Route::get('/berita', 'FrontController@index')->name('berita');
Route::get('/berita/{id}', 'FrontController@shownews')->name('lihatberita');

// Route::resource('dashboard/profile', 'ProfileController');
// Route::resource('dashboard/news', 'NewsController');
// Route::resource('dashboard/comment', 'CommentController');

Route::resource('dashboard/profile', 'ProfileController');
Route::resource('dashboard/news', 'NewsController');
Route::resource('dashboard/comment', 'CommentController');

Route::get('/dashboard/comments/pdf', 'CommentController@CetakPDF');
Route::get('/dashboard/comments/excel', 'CommentController@CetakExcel');
// Route::resource('/dashboard/comments', 'CommentController');


Route::get('/test1', 'PdfController@test1');
Route::get('/test2', 'PdfController@test2');

Route::get('/dashboard/profile', 'ProfileController@show')->middleware('auth');
Route::post('/dashboard/profile', 'ProfileController@store');
Route::get('/dashboard/profile/{profile_id}/edit', 'ProfileController@edit');
Route::put('/dashboard/profile/{profil_id}', 'ProfileController@update');

// Report
Route::get('/dashboard/report/users', 'ReportController@reportUserToExcel');
Route::get('/dashboard/report/news', 'ReportController@reportNewsToExcel');

Route::get('topdf/{id}', 'FrontController@topdf')->name('topdf');
Route::get('tag/{tag}', 'TagController@filter')->name('tagname');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
   /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'news';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title','image','body','user_id'];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'is_publish' => 'boolean',
    ];

    /**
     * Get the user that create a News.
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    /**
     * Get the comment record associated with the News.
     */
    public function comment()
    {
        return $this->hasMany('App\Comment');
    }
    
    /**
     * Get the tag record associated with the News.
     */
    public function tag()
    {
        return $this->belongsToMany('App\Tag');
    }


}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\News;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;
class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = News::with(['user','tag'])->get();
        return view('backend.news.index', ['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::all();
        return view('backend.news.create',['tags' => $tags]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

         $arrIdTag=[];
        foreach($request->tags as $value) {
            //cherk apakah valuenya integer
            if(is_numeric($value)){
                // cari tag dalam value
                // kalo gak ada bvaluenya di create
                // kalo gak ada langhsung di push ke array
                if(Tag::find($value) ==  null) {
                    //kita buat database baru numeric
                    Tag::create([
                        'name' => $value,
                    ]);

                    $idTags = Tag::where('name', $value)->first();

                    $arrIdTag[] = strval($idTags['id']);

                } else {
                    //gak ada di databse
                     $arrIdTag[] = strval($value);
                }

            }else {

                if(Tag::where('name', $value)->first() == null){
                    Tag::create([
                        'name' => $value,
                    ]);
    
                    $idTags = Tag::where('name', $value)->first();
                    
                    $arrIdTag[] = strval($idTags['id']);
                } else {
                    $idTags = Tag::where('name', $value)->first();
                    
                    $arrIdTag[] = strval($idTags['id']);
                }
            }
        }

        $imageName = time().'.'.$request->image->extension();

        $request->image->move(public_path('frontend/upload'), $imageName);

        $news = News::create([
            'title' => $request['title'],
            'image' => $imageName,
            'body' => $request['body'],
            'is_publish' => $request['is_publish'],
            'user_id' => Auth::id()
        ]);

        $news->tag()->attach($arrIdTag);

        Alert::success('Success Title', 'Data Telah Tersimoan');

        return redirect()->route('news.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\News  $news
     * @return \Illuminate\Http\Response
     */
    public function show(News $news)
    {
        //$data = News::find($news)->first();
        $tags = Tag::all();
        return view('backend.news.view',['data'=>$news, 'tags' => $tags]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\News  $news
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {
        //echo $news;
        //$data = News::where('id',$news->id)->first();
        $tags = Tag::all();
        return view('backend.news.edit',['data'=>$news, 'tags' => $tags]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\News  $news
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, News $news)
    {
        if($request['image'] == null) {
            $imageName=$news->image;
        } else {
            unlink('frontend/upload/'.$news->image);
            //$imageName = 'sampeimag.jpg';
            $imageName = time().'.'.$request->image->extension();
            $request->image->move(public_path('frontend/upload'), $imageName);
        };

        if ($request['is_publish'] == null) {
            $is_publish=$news->is_publish;
        } else {
            $is_publish=$request['is_publish'];
        };

        ///array converter array
         $arrIdTag=[];
        foreach($request->tags as $value) {
            //cherk apakah valuenya integer
            if(is_numeric($value)){
                // cari tag dalam value
                // kalo gak ada bvaluenya di create
                // kalo gak ada langhsung di push ke array
                if(Tag::find($value) ==  null) {
                    //kita buat database baru numeric
                    Tag::create([
                        'name' => $value,
                    ]);

                    $idTags = Tag::where('name', $value)->first();

                    $arrIdTag[] = strval($idTags['id']);

                } else {
                    //gak ada di databse
                     $arrIdTag[] = strval($value);
                }

            }else {

                if(Tag::where('name', $value)->first() == null){
                    Tag::create([
                        'name' => $value,
                    ]);
    
                    $idTags = Tag::where('name', $value)->first();
                    
                    $arrIdTag[] = strval($idTags['id']);
                } else {
                    $idTags = Tag::where('name', $value)->first();
                    
                    $arrIdTag[] = strval($idTags['id']);
                }
            }
        }


        News::where('id', $news->id)->update([
            'title' => $request['title'],
            'image' => $imageName,
            'body' => $request['body'],
            'is_publish' => $is_publish,
            'user_id' => Auth::id()
        ]);


        $news->tag()->sync($arrIdTag);

        Alert::success('Success Title', 'Data Telah Di Update');

        return redirect()->route('news.index');
     }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\News  $news
     * @return \Illuminate\Http\Response
     */
    public function destroy(News $news)
    {   
        if(file_exists('frontend/upload/'.$news->image)){
        unlink('frontend/upload/'.$news->image);
        }
        News::destroy($news->id);
        Alert::success('Success Title', 'Data Telah Di Update');
        return redirect()->route('news.index');
    }
}

resources/views/backend/news/create.blade.php
@extends('layouts.backend.master')

@push('styles')
<link rel="stylesheet" href="{{ asset('backend/plugins/summernote/summernote-bs4.css') }}">
 <!-- Select2 -->
<link rel="stylesheet" href="{{ asset('backend/plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('backend/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}>
@endpush

@section('page_active', 'News')
@section('action', 'Create')

@section('content')

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Create News</h3>
                    </div>
                    <form method="POST" action="{{ route('news.store') }}" enctype="multipart/form-data">
                        @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="title">{{ __('Judul') }}</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" id="title" placeholder="Masukan Judul" value="{{ old('title') }}" required autocomplete="title" autofocus>
                            @error('title')
                            <p>Eror :<code>{{ $message }}</code></p>
                            @enderror
                        </div>
                        <div class="mb-3">
                        <label for="body">{{ __('Berita') }}</label>
                        <textarea id="textarea" class="form-control textarea" name="body" style="height: 300px">{{ old('title') }}</textarea>
                        @error('body')
                            <p>Eror :<code>{{ $message }}</code></p>
                        @enderror
                        </div>
                        <div class="form-group">
                            <label>Tag</label>
                            <div class="select2-blue">
                                <select class="select2" name="tags[]" multiple="multiple" data-placeholder="Pilih Tag" data-dropdown-css-class="select2-blue" style="width: 100%;">
                                @foreach($tags as $tag)
                                <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                                @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="image">Input Gambar</label>
                            <div class="input-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="image" name="image">
                                <label class="custom-file-label" for="image">Choose file</label>
                            </div>
                            </div>
                            @error('image')
                            <p>Eror :<code>{{ $message }}</code></p>
                            @enderror
                        </div>
                        <div class="form-group">
                            <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="is_publish" value="0">
                            <label class="form-check-label">Sembunyikan</label>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
</section>

@endsection

@push('scripts')
<!-- bs-custom-file-input -->
<script src="{{ asset('backend/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
 <!-- Summernote -->
 <script src="{{ asset('backend/plugins/summernote/summernote-bs4.min.js') }}"></script>
 <!-- Select2 -->
<script src="{{ asset('backend/plugins/select2/js/select2.full.min.js') }}"></script>
<script>
  $(function () {
    // Summernote
    $('.textarea').summernote({
        height: 300,
    })
  })

  $(document).ready(function () {
  bsCustomFileInput.init();
});

//Initialize Select2 Elements
$('.select2').select2( {
    tags:true
})
</script>
@endpush

resources/views/backend/news/edit.blade.php
@extends('layouts.backend.master')

@push('styles')
<link rel="stylesheet" href="{{ asset('backend/plugins/summernote/summernote-bs4.css') }}">
 <!-- Select2 -->
<link rel="stylesheet" href="{{ asset('backend/plugins/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('backend/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}>
@endpush

@section('page_active', 'News')
@section('action', 'Create')

@section('content')

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Create News</h3>
                    </div>
                    <form method="POST" action="{{ route('news.update',$data->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                    <div class="card-body">
                        <div class="form-group">
                            <label for="title">{{ __('Judul') }}</label>
                            <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" id="title" placeholder="Masukan Judul" value="{{ old('title',$data->title) }}" required autocomplete="title" autofocus>
                            @error('title')
                            <p>Eror :<code>{{ $message }}</code></p>
                            @enderror
                        </div>
                        <div class="mb-3">
                        <label for="body">{{ __('Berita') }}</label>
                        <textarea id="body" name="body" class="textarea" placeholder="Berita">{{ old('body',$data->body) }}</textarea>
                        @error('news')
                            <p>Eror :<code>{{ $message }}</code></p>
                        @enderror
                        </div>
                        <div class="form-group">
                            <label>Tag</label>
                            <div class="select2-purple">
                                <select class="select2" name="tags[]" multiple="multiple" data-placeholder="Select a State" data-dropdown-css-class="select2-purple" style="width: 100%;">
                                @foreach($tags as $tag)
                                <!-- Halo Master, Help Me  -->
                                <!-- Bagimana menampilkan tag yang berelasi di menu edit agar terselected tapi keseluruhan tabel tag juga keluar -->
                                <!-- Looping semua data di table tag -->
                                <!-- jika id table tag == id table tag yang berelasi dengan berita echo selectd -->
                                <!-- CARA LOOPINGNYA GIMANA?? -->
                                <!-- Kalo ada sample codingnya sangat berterimakasih -->
                                <option value="{{ $tag->id }}"
                                    @foreach($data->tag as $value) 
                                    @if($tag->id == $value->id)
                                    selected
                                    @endif
                                    @endforeach
                                >{{ $tag->name }}</option>
                                @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="image">Input Gambar</label>
                            <div class="input-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="image" name="image" value="{{$data->image}}">
                                <label class="custom-file-label" for="image">{{$data->image}}</label>
                            </div>
                            </div>
                            @error('news')
                            <p>Eror :<code>{{ $message }}</code></p>
                            @enderror
                        </div>
                        <div class="form-group">
                            
                            @if($data->is_publish == 0)
                            <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="is_publish" value="1">
                            <label class="form-check-label">Tampilkan</label>
                            </div>
                            @else
                            <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="is_publish" value="0">
                            <label class="form-check-label">Sembunyikan</label>
                            </div>
                            @endif
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
</section>

@endsection

@push('scripts')
<!-- bs-custom-file-input -->
<script src="{{ asset('backend/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
 <!-- Summernote -->
 <script src="{{ asset('backend/plugins/summernote/summernote-bs4.min.js') }}"></script>
 <!-- Select2 -->
<script src="{{ asset('backend/plugins/select2/js/select2.full.min.js') }}"></script>
<script>
  $(function () {
    // Summernote
    $('.textarea').summernote({
        height: 300,
    })
  })

  $(document).ready(function () {
  bsCustomFileInput.init();
});

//Initialize Select2 Elements
$('.select2').select2({
    tags:true
})
</script>
@endpush

resources/views/backend/news/index.blade.php
@extends('layouts.backend.master')

@section('page_info')
<a href="{{ url('/dashboard/news/create')}}" class="px-4 mt-2 btn btn-primary btn-sm">
    <i class="mr-2 fas fa-plus"></i>Tambah Data</a>
@endsection

@section('page_active', 'News')
@section('action', 'Index')

@section('content')

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">List News</h3>
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Judul</th>
                                    <th>Isi</th>
                                    <th>Author</th>
                                    <th>Tags</th>
                                    <th>Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($data as $news)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $news->title }}</td>
                                    <td>{!! Str::limit($news->body,300,'(...)') !!}</td>
                                    <td>{{ $news->user->name }}</td>
                                    <td>
                                        @foreach($news->tag as $tagname)
                                        <a href="{{ route('tagname', $tagname->id) }}"><span
                                                class="badge bg-primary">{{ $tagname->name }}</span></a>
                                        @endforeach
                                    </td>
                                    <td>{{ $news->updated_at }}</td>
                                    <td>
                                        <a href="{{ route('news.show', $news->id) }}"><button type="button"
                                                class="btn btn-block btn-default" style="margin:3px;">Lihat</button></a>
                                        <a href="{{ route('news.edit', $news->id) }}"><button type="button"
                                                class="btn btn-block btn-warning" style="margin:3px;">Edit</button></a>
                                        <form action="{{ route('news.destroy', $news->id)}}" method="POST"
                                            class="delete-confirm">
                                            @csrf
                                            @method('DELETE')
                                            <input type="submit" class="btn btn-danger btn-block" style="margin:3px;"
                                                value="Delete">
                                        </form>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@endsection

@push('scripts')
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
    $('.delete-confirm').on('submit', function(e){
    var form = this;
    event.preventDefault();
    swal({
        title: 'Are you sure?',
        text: 'This record and it`s details will be permanantly deleted!',
        icon: 'warning',
        buttons: ["Cancel", "Yes!"],
    }).then(function(value) {
        if (value) {
            return form.submit();
        }
    });
});
</script>
@endpush

resources/views/backend/news/view.blade.php
@extends('layouts.backend.master')

@section('page_active', 'News')
@section('action', 'View')

@section('content')

<section class="content">
    <div class="container-fluid">
    <div class="row">
          <div class="col-12">
            <!-- Default box -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">{{ $data->title }}</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fas fa-times"></i></button>
                </div>
              </div>
              <div class="card-body">
                {!! $data->body !!}
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
              @foreach($data->tag as $tagname)
              <a href="{{ route('tagname', $tagname->id ) }}"><span class="badge bg-success">{{ $tagname->name }}</span></a>
              @endforeach
              </div>
              <!-- /.card-footer-->
            </div>
            <!-- /.card -->
          </div>
        </div>
    </div>
    </div>
</section>

@endsection